$files = Get-ChildItem "taxi\*.html"
$map = [ordered]@{}

$k = @(
"est?s","estas"
"tendr?s","tendras"
"Recibir?s","Recibiras"
"Llegar?s","Llegaras"
"usar?n","usaran"
"av?sanos","avisanos"
"dep?sitos","depositos"
"d?a","dia"
"beb?","bebe"
"lleg?","llego"
"Conf?a","Confia"
"Dal?","Dali"
"Vall?s","Valles"
"Adri?","Adria"
"Barcelon?s","Barcelones"
"Catalu?a","Cataluna"
"monta?a","montana"
"tama?o","tamano"
"dise?ado","disenado"
"redise?ado","redisenado"
"se?alizadas","senalizadas"
"acompa?antes","acompanantes"
"peque?os","pequenos"
"peque?o","pequeno"
"peque?a","pequena"
"ni?os","ninos"
"a?os","anos"
"rese?as","resenas"
"Rese?as","Resenas"
"Espa?ola","Espanola"
"compa??a","compania"
"acompa?amiento","acompanamiento"
"?Hablamos","?Hablamos"
"?Necesitas","?Necesitas"
"?Llegas","?Llegas"
"?Cubres","?Cubres"
"?Tienes","?Tienes"
"?Vuelves","?Vuelves"
"?Qu?","?Que"
"?gil","agil"
"?ndole","indole"
"atenci?n","atencion"
"facturaci?n","facturacion"
"conexi?n","conexion"
"informaci?n","informacion"
"navegaci?n","navegacion"
"configuraci?n","configuracion"
"actualizaci?n","actualizacion"
"promoci?n","promocion"
"reproducci?n","reproduccion"
"distribuci?n","distribucion"
"modificaci?n","modificacion"
"exenci?n","exencion"
"legislaci?n","legislacion"
"conservaci?n","conservacion"
"ejecuci?n","ejecucion"
"contrataci?n","contratacion"
"infracci?n","infraccion"
"comunicaci?n","comunicacion"
"personalizaci?n","personalizacion"
"cancelaci?n","cancelacion"
"excursi?n","excursion"
"ocasi?n","ocasion"
"antelaci?n","antelacion"
"valoraci?n","valoracion"
"Confirmaci?n","Confirmacion"
"formaci?n","formacion"
"climatizaci?n","climatizacion"
"regulaci?n","regulacion"
"supresi?n","supresion"
"obligaci?n","obligacion"
"reclamaci?n","reclamacion"
"Protecci?n","Proteccion"
"documentaci?n","documentacion"
"conducci?n","conduccion"
"estaci?n","estacion"
"regi?n","region"
"relaci?n","relacion"
"sujeci?n","sujecion"
"suspensi?n","suspension"
"vinculaci?n","vinculacion"
"monitorizaci?n","monitorizacion"
"insonorizaci?n","insonorizacion"
"Legitimaci?n","Legitimacion"
"Conservaci?n","Conservacion"
"trav?s","traves"
"tambi?n","tambien"
"Tambi?n","Tambien"
"Gesti?n","Gestion"
"Duraci?n","Duracion"
"Pol?tica","Politica"
"pol?tica","politica"
"pol?ticas","politicas"
"?rea","Area"
"im?genes","imagenes"
"Men?","Menu"
"Ll?manos","Llamanos"
"?ltima","Ultima"
"da?os","danos"
"c?mo","como"
"d?nde","donde"
"cu?ndo","cuando"
"M?laga","Malaga"
"avi?n","avion"
"espec?fica","especifica"
"espec?ficas","especificas"
"Anal?ticas","Analiticas"
"an?nima","anonima"
"b?sico","basico"
"t?cnicas","tecnicas"
"t?cnica","tecnica"
"t?cnico","tecnico"
"Secci?n","Seccion"
"Cont?ctanos","Contactanos"
"Descripci?n","Descripcion"
"tr?fico","trafico"
"p?gina","pagina"
"garant?as","garantias"
"garant?a","garantia"
"el?ctrica","electrica"
"el?ctrico","electrico"
"leg?timo","legitimo"
"Bel?n","Belen"
"monovol?menes","monovolumenes"
"Sesi?n","Sesion"
"repetir?","repetira"
"modificacio?n","modificacion"
"geograf?a","geografia"
"geogr?fica","geografica"
"Instrucci?n","Instruccion"
"secci?n","seccion"
"petici?n","peticion"
"pacienci?","paciencia"
"experienci?","experiencia"
"n?mero","numero"
"tel?fono","telefono"
"veh?culo","vehiculo"
"aerol?neas","aerolineas"
"cubiert?","cubierta"
"situaci?n","situacion"
"direcci?n","direccion"
"dise?o","diseno"
"autorizaci?n","autorizacion"
"espa?ol","espanol"
"veh?culos","vehiculos"
"Veh?culos","Vehiculos"
"Tel?fono","Telefono"
"m?s ","mas "
"M?s ","Mas "
"t? ","tu "
"T? ","Tu "
"s? ","si "
"S? ","Si "
"Qu?","Que"
"T?","Tu"
"est?n","estan"
"est?","esta"
"autom?tico","automatico"
"m?xima","maxima"
"m?ximo","maximo"
"m?nimo","minimo"
"r?pidos","rapidos"
"p?blico","publico"
"p?rdida","perdida"
"p?rdidas","perdidas"
"emblem?ticos","emblematicos"
"m?dica","medica"
"m?dicas","medicas"
"m?dico","medico"
"despu?","despues"
"atr?s","atras"
"arn?s","arnes"
"estr?s","estres"
"inter?s","interes"
"autob?s","autobus"
"h?brido","hibrido"
"neum?tica","neumatica"
"peri?dicamente","periodicamente"
"peri?dicas","periodicas"
"d?as","dias"
"c?ntimo","centimo"
"seg?n","segun"
"c?modamente","comodamente"
"aceptaci?n","aceptacion"
"c?moda","comoda"
"c?modo","comodo"
"alg?n","algun"
"aqu?","aqui"
"publicidad","publicidad"
"Preg?ntanos","Preguntanos"
"Cont?ctanos","Contactanos"
"espiritu?","espiritu"
"Veh?culo","Vehiculo"
"despu?sp","despues"
"atr?sp","atras"
"peque?ap","pequena"
"reclamaci?","reclamacion"
"Barcelona?","Barcelona"
"ciudad?h2","ciudad"
"Girona?Costa","Girona-Costa"
"Vall?sp","Valles"
"autob?sp","autobus"
"nacional?","nacional"
"servicio?","servicio"
"crucero?","crucero"
"intermedia?","intermedia"
"viaje?","viaje"
"zona?a","zona a"
"algo?","algo"
)

for ($i = 0; $i -lt $k.Count; $i += 2) {
  if (!$map.Contains($k[$i])) { $map[$k[$i]] = $k[$i+1] }
}

$total = 0
foreach ($f in $files) {
  $text = [System.Text.Encoding]::UTF8.GetString([System.IO.File]::ReadAllBytes($f.FullName))
  $orig = $text
  $cnt = 0
  foreach ($key in $map.Keys) {
    if ($text.Contains($key)) {
      $c = [regex]::Matches($text, [regex]::Escape($key)).Count
      $text = $text -replace [regex]::Escape($key), $map[$key]
      $cnt += $c
    }
  }
  if ($cnt -gt 0) {
    [System.IO.File]::WriteAllBytes($f.FullName, [System.Text.Encoding]::UTF8.GetBytes($text))
    "$($f.Name) ($cnt)"
    $total += $cnt
  }
}
"Total: $total"
